# https://taskfile.dev

version: '3'


tasks:
  uv-sync:
    cmds:
      - uv sync --all-groups --all-extras
      - uv pip install -e .
  dagster:
    cmds:
      - DAGSTER_HOME=$(pwd)/.dagster uv run dagster dev