resources:
  queries:
    config:
      queries:
        # Yue
        - lon: -0.105971
          lat: 51.515615
          max_duration: 40
        # Cemlyn
        - lon: -0.1299217
          lat: 51.5194938
          max_duration: 30
  smtp:
    config:
      to_addresses:
        - cemlynwaters@gmail.com
        - iamyue.hu@gmail.com
